<?php
use PingCAP\Constants;

$acf_group = 'user_day';

//イベントページでflg_user_dayが有効な場合テンプレートを変更する。
function custom_user_day_template_include( $template ) {
    if ( is_singular( 'event' ) || is_singular( 'page' ) ) {
        global $post;
        //カスタムフィールドflg_user_dayの値を取得
        $flg_user_day = get_post_meta($post->ID, 'flg_user_day', true);
        //flg_user_dayがtrueの場合、テンプレートを変更
        if($flg_user_day){
            $new_template = locate_template( array( 'templates/page-user-day.php' ) );
            if ( '' != $new_template ) {
                return $new_template ;
            }
        }
    }
    return $template;
}
add_filter( 'template_include', 'custom_user_day_template_include', 99 );

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_6629b21e5e2cd',
	'title' => 'New Event Template',
	'fields' => array(
		array(
			'key' => 'field_6665c57a3da97',
			'label' => 'New Event Templateを利用する',
			'name' => 'flg_user_day',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
		array(
			'key' => 'field_6665dde8c3c69',
			'label' => 'New Event',
			'name' => 'user_day_section',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6665c57a3da97',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_66a338720af27',
					'label' => 'キービジュアル',
					'name' => 'mv',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_66a3389c0af28',
							'label' => 'PC用',
							'name' => 'pc',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_66a338af0af29',
							'label' => 'SP用',
							'name' => 'sp',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
						),
					),
				),
				array(
					'key' => 'field_6666a4d11995b',
					'label' => 'タグ',
					'name' => 'tag',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6665de4865791',
					'label' => 'イベントについて',
					'name' => 'about',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_6665de6a65792',
							'label' => '見出し',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6665de8065793',
							'label' => '概要',
							'name' => 'detail',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'rows' => 4,
							'placeholder' => '',
							'new_lines' => '',
						),
					),
				),
				array(
					'key' => 'field_6665deb365794',
					'label' => '開催概要',
					'name' => 'overview',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_6665dece65795',
							'label' => '開催日',
							'name' => 'date',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6665dee565796',
							'label' => '時間',
							'name' => 'time',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6665def265797',
							'label' => '形式',
							'name' => 'format',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6665df1e65798',
							'label' => '主催',
							'name' => 'sponsorship',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6665df3465799',
							'label' => '参加費',
							'name' => 'fee',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
					),
				),
				array(
					'key' => 'field_6629b29ef3b94',
					'label' => 'ルーム',
					'name' => 'room',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'pagination' => 0,
					'min' => 1,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'ルームを追加',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_6665d3c08d2d5',
							'label' => 'ルーム名',
							'name' => 'name',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_6629b29ef3b94',
						),
						array(
							'key' => 'field_6629b22cf3b93',
							'label' => 'プログラム',
							'name' => 'program',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 1,
							'max' => 0,
							'layout' => 'block',
							'button_label' => 'プログラムを追加',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_6629b313f3b95',
									'label' => '見出し',
									'name' => 'title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '40',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'parent_repeater' => 'field_6629b22cf3b93',
								),
								array(
									'key' => 'field_6629b345f3b97',
									'label' => '開始時間',
									'name' => 'start',
									'aria-label' => '',
									'type' => 'time_picker',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '30',
										'class' => '',
										'id' => '',
									),
									'display_format' => 'H:i',
									'return_format' => 'H:i',
									'parent_repeater' => 'field_6629b22cf3b93',
								),
								array(
									'key' => 'field_6629b37ff3b98',
									'label' => '終了時間',
									'name' => 'end',
									'aria-label' => '',
									'type' => 'time_picker',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '30',
										'class' => '',
										'id' => '',
									),
									'display_format' => 'H:i',
									'return_format' => 'H:i',
									'parent_repeater' => 'field_6629b22cf3b93',
								),
								array(
									'key' => 'field_6665d53d8b814',
									'label' => '休憩時間に設定する',
									'name' => 'break',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'ui' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'parent_repeater' => 'field_6629b22cf3b93',
								),
								array(
									'key' => 'field_6629b325f3b96',
									'label' => 'テキスト',
									'name' => 'text',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_6665d53d8b814',
												'operator' => '!=',
												'value' => '1',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'rows' => 4,
									'placeholder' => '',
									'new_lines' => 'br',
									'parent_repeater' => 'field_6629b22cf3b93',
								),
								array(
									'key' => 'field_6629b7e6d3b51',
									'label' => 'リンク',
									'name' => 'links',
									'aria-label' => '',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_6665d53d8b814',
												'operator' => '!=',
												'value' => '1',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'block',
									'min' => 0,
									'max' => 0,
									'collapsed' => '',
									'button_label' => 'リンクを追加',
									'rows_per_page' => 20,
									'sub_fields' => array(
										array(
											'key' => 'field_666a711cc8ccc',
											'label' => 'テキスト',
											'name' => 'text',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '30',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'parent_repeater' => 'field_6629b7e6d3b51',
										),
										array(
											'key' => 'field_6629b8b3d3b52',
											'label' => 'URL',
											'name' => 'url',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '40',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'parent_repeater' => 'field_6629b7e6d3b51',
										),
										array(
											'key' => 'field_6629be4ed3b54',
											'label' => '種別',
											'name' => 'type',
											'aria-label' => '',
											'type' => 'select',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '30',
												'class' => '',
												'id' => '',
											),
											'choices' => array(
												'link' => '通常リンク',
												'movie' => '動画モーダル',
											),
											'default_value' => false,
											'return_format' => 'value',
											'multiple' => 0,
											'allow_null' => 0,
											'ui' => 0,
											'ajax' => 0,
											'placeholder' => '',
											'parent_repeater' => 'field_6629b7e6d3b51',
										),
									),
									'parent_repeater' => 'field_6629b22cf3b93',
								),
								array(
									'key' => 'field_6629bed1d3b55',
									'label' => '登壇者',
									'name' => 'speakers',
									'aria-label' => '',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_6665d53d8b814',
												'operator' => '!=',
												'value' => '1',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'block',
									'min' => 0,
									'max' => 0,
									'collapsed' => '',
									'button_label' => '登壇者を追加',
									'rows_per_page' => 20,
									'sub_fields' => array(
										array(
											'key' => 'field_6629bef2d3b56',
											'label' => '画像',
											'name' => 'image',
											'aria-label' => '',
											'type' => 'image',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '30',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'array',
											'preview_size' => 'medium',
											'library' => 'all',
											'min_width' => '',
											'min_height' => '',
											'min_size' => '',
											'max_width' => '',
											'max_height' => '',
											'max_size' => '',
											'mime_types' => '',
											'parent_repeater' => 'field_6629bed1d3b55',
										),
										array(
											'key' => 'field_6629c099d3b57',
											'label' => '名前',
											'name' => 'name',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '30',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
											'parent_repeater' => 'field_6629bed1d3b55',
										),
										array(
											'key' => 'field_6629c0b0d3b58',
											'label' => 'テキスト',
											'name' => 'text',
											'aria-label' => '',
											'type' => 'textarea',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '40',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'maxlength' => '',
											'rows' => 2,
											'new_lines' => 'br',
											'parent_repeater' => 'field_6629bed1d3b55',
										),
									),
									'parent_repeater' => 'field_6629b22cf3b93',
								),
								array(
									'key' => 'field_6629c1eda7383',
									'label' => 'タグ',
									'name' => 'tags',
									'aria-label' => '',
									'type' => 'taxonomy',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_6665d53d8b814',
												'operator' => '!=',
												'value' => '1',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'taxonomy' => 'userdaytag',
									'add_term' => 1,
									'save_terms' => 0,
									'load_terms' => 0,
									'return_format' => 'id',
									'field_type' => 'multi_select',
									'allow_null' => 0,
									'bidirectional' => 0,
									'multiple' => 0,
									'bidirectional_target' => array(
									),
									'parent_repeater' => 'field_6629b22cf3b93',
								),
							),
							'parent_repeater' => 'field_6629b29ef3b94',
						),
						array(
							'key' => 'field_6666a5001995c',
							'label' => '注意書き',
							'name' => 'note',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_6629b29ef3b94',
						),
					),
				),
				array(
					'key' => 'field_6665df4f6579a',
					'label' => 'イベント用 大画像',
					'name' => 'company',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_66a9048005bd8',
							'label' => 'タイトル',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '未入力の場合、エリアが非表示になります。',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6666ac6a83d20',
							'label' => 'pc',
							'name' => 'pc',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_6666ac7883d21',
							'label' => 'sp',
							'name' => 'sp',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
						),
					),
				),
				array(
					'key' => 'field_666a7ae598c1d',
					'label' => 'キャンペーンタイトル',
					'name' => 'campaign_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6665dfefc7100',
					'label' => 'キャンペーン',
					'name' => 'campaign',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'text',
					'media_upload' => 1,
					'toolbar' => 'full',
					'delay' => 0,
				),
				array(
					'key' => 'field_666a7b0f98c1e',
					'label' => 'インフルエンサープログラムタイトル',
					'name' => 'influencer_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_666a797589ee4',
					'label' => 'インフルエンサープログラム',
					'name' => 'influencer',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'text',
					'media_upload' => 1,
					'toolbar' => 'full',
					'delay' => 0,
				),
				array(
					'key' => 'field_6665e018c7101',
					'label' => '参加申込',
					'name' => 'application',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'text',
					'media_upload' => 1,
					'toolbar' => 'full',
					'delay' => 0,
				),
				array(
					'key' => 'field_666a7a4b98c1c',
					'label' => '参加申込を表示する',
					'name' => 'cta_btn',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'event',
			),
		),
		array(
			array(
				'param' => 'post_template',
				'operator' => '==',
				'value' => 'templates/page-user-day.php',
			),
		),
	),
	'menu_order' => 10,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );




