<?php
/*
* Gravitate Content Block
*
* Available Variables:
* $block                  = Name of Block Folder
* $block_backgrounds      = Array for Background Options
* $block_background_image = Array for Background Image Option
*
* This file must return an array();
*/

$block_fields = array(
	array(
		'key' => 'field_' . $block . '_block_eyebrow',
		'label' => 'Block Eyebrow',
		'name' => 'block_eyebrow',
		'type' => 'text',
		'instructions' => 'Small text displayed above the block title',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'formatting' => 'none',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
		'readonly' => 0,
		'disabled' => 0,
	),
	array(
		'key' => 'field_' . $block . '_block_title',
		'label' => 'Block Title',
		'name' => 'block_title',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'formatting' => 'none',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
		'readonly' => 0,
		'disabled' => 0,
	),
	array(
		'key' => 'field_' . $block . '_block_desc',
		'label' => 'Block Description',
		'name' => 'block_desc',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'formatting' => 'none',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
		'readonly' => 0,
		'disabled' => 0,
	),
	array(
		'key' => 'field_' . $block . '_view_all_link',
		'label' => 'View All Link',
		'name' => 'view_all_link',
		'type' => 'url',
		'instructions' => 'Link for "View all customer stories"',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
	),
	array(
		'key' => 'field_' . $block . '_view_all_text',
		'label' => 'View All Text',
		'name' => 'view_all_text',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => 'View all customer stories',
		'placeholder' => '',
		'formatting' => 'none',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
		'readonly' => 0,
		'disabled' => 0,
	),
	array(
		'key' => 'field_' . $block . '_case_cards',
		'label' => 'Cards',
		'name' => 'case_cards',
		'type' => 'repeater',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'collapsed' => '',
		'min' => 1,
		'max' => '',
		'layout' => 'block',
		'button_label' => 'Add Card',
		'sub_fields' => array_merge(
			array(
				array(
					'key' => 'field_' . $block . '_card_tag_color',
					'label' => 'Tag Color',
					'name' => 'tag_color',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'red' => 'Red',
						'blue' => 'Blue',
						'violet' => 'Violet',
						'green' => 'Green',
					),
					'default_value' => 'red',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
				),
				array(
					'key' => 'field_' . $block . '_card_tag',
					'label' => 'Tag',
					'name' => 'tag',
					'type' => 'text',
					'instructions' => 'Category tag displayed at the top of the card (e.g. "AGENTIC AI", "SAAS")',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '70',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'formatting' => 'none',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_' . $block . '_card_company_name',
					'label' => 'Company Name',
					'name' => 'company_name',
					'type' => 'text',
					'instructions' => 'Displayed when no logo is provided',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'formatting' => 'none',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_' . $block . '_card_logo',
					'label' => 'Logo',
					'name' => 'logo',
					'type' => 'image',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'object',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_' . $block . '_card_title',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'formatting' => 'none',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_' . $block . '_card_desc',
					'label' => 'Description',
					'name' => 'desc',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => "\n",
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_' . $block . '_card_stat_1_value',
					'label' => 'Stat 1 Value',
					'name' => 'stat_1_value',
					'type' => 'text',
					'instructions' => 'e.g. "2 wks", "3M+"',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'formatting' => 'none',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_' . $block . '_card_stat_1_label',
					'label' => 'Stat 1 Label',
					'name' => 'stat_1_label',
					'type' => 'text',
					'instructions' => 'e.g. "Migration time"',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'formatting' => 'none',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_' . $block . '_card_stat_2_value',
					'label' => 'Stat 2 Value',
					'name' => 'stat_2_value',
					'type' => 'text',
					'instructions' => 'e.g. "1M+", "750+"',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'formatting' => 'none',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_' . $block . '_card_stat_2_label',
					'label' => 'Stat 2 Label',
					'name' => 'stat_2_label',
					'type' => 'text',
					'instructions' => 'e.g. "DB tenants"',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'formatting' => 'none',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				)
			),
			WPUtil\Vendor\BlueprintBlocks::safe_get_link_fields([
				'label' => 'Link',
				'name' => 'link',
				'key_modifier' => 'case_slide_card',
				'includes' => [
					'page' => 'Page Link',
					'url' => 'URL',
					'none' => 'None',
				],
				'supports_button_styles' => false,
			]),
		)
	),
);

return array(
	'label' => 'Case Slide',
	'name' => $block,
	'display' => 'block',
	'min' => '',
	'max' => '',
	'sub_fields' => $block_fields,
	'grav_blocks_settings' => array(
		'icon' => 'gravicon-title',
		'description' => ''
	)
);
